[package]
name = "transfer-role-features-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.transfer-role-features]
path = ".."

[dependencies.numbat-wasm-debug]
version = "0.0.18"
path = "../../../../../numbat-wasm-debug"
