[package]
name = "abi-tester"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2024"
publish = false

[lib]
path = "src/abi_tester.rs"

[dependencies.dharitri-sc]
version = "2.0.0"
path = "../../../framework/base"
features = ["alloc"]

[dev-dependencies.dharitri-sc-scenario]
version = "2.0.0"
path = "../../../framework/scenario"

[dev-dependencies.dharitri-sc-meta-lib]
version = "2.0.0"
path = "../../../framework/meta-lib"

[dependencies]
bitflags = "2.9"
