[package]
name = "basic-features-meta"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2018"
publish = false

[dependencies.basic-features]
path = ".."

[dependencies.numbat-wasm-debug]
version = "0.0.18"
path = "../../../../numbat-wasm-debug"
