[package]
name = "dcdt-contract-pair"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2024"
publish = false

[dev-dependencies.first-contract]
path = "first-contract"

[dev-dependencies.second-contract]
path = "second-contract"

[dev-dependencies.dharitri-sc]
version = "2.0.0"
path = "../../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "2.0.0"
path = "../../../../framework/scenario"
