[package]
name = "dcdt-contract-pair"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"


[dependencies.first-contract]
path = "first-contract"

[dependencies.second-contract]
path = "second-contract"

[dependencies.numbat-wasm]
version = "0.0.18"
path = "../../../../numbat-wasm"

[dev-dependencies.numbat-wasm-debug]
version = "0.0.18"
path = "../../../../numbat-wasm-debug"
