[package]
name = "ping-pong-rewa"
version = "0.0.2"
authors = [ "Dharitri <contact@dharitri.org>",]
edition = "2024"
publish = false

[lib]
path = "src/ping_pong.rs"

[dependencies.dharitri-sc]
version = "2.0.0"
path = "../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "2.0.0"
features = ["wasmer-experimental"]
path = "../../../framework/scenario"

