[package]
name = "composability-tests"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2024"
publish = false

[dev-dependencies.builtin-func-features]
path = "builtin-func-features"

[dev-dependencies.forwarder]
path = "forwarder"

[dev-dependencies.forwarder-legacy]
path = "forwarder-legacy"

[dev-dependencies.forwarder-queue]
path = "forwarder-queue"

[dev-dependencies.forwarder-raw]
path = "forwarder-raw"

[dev-dependencies.proxy-test-first]
path = "proxy-test-first"

[dev-dependencies.proxy-test-second]
path = "proxy-test-second"

[dev-dependencies.recursive-caller]
path = "recursive-caller"

[dev-dependencies.vault]
path = "vault"

[dependencies.dharitri-sc]
version = "2.0.0"
path = "../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "2.0.0"
path = "../../../framework/scenario"
features = ["wasmer-experimental"]
