[package]
name = "erc1155-user-mock-meta"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2024"
publish = false

[dependencies.erc1155-user-mock]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "2.0.0"
path = "../../../../../framework/meta-lib"
default-features = false
