[package]
name = "erc1155-user-mock-meta"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2018"
publish = false

[dependencies.erc1155-user-mock]
path = ".."

[dependencies.numbat-wasm-debug]
version = "0.0.18"
path = "../../../../../numbat-wasm-debug"
