[package]
name = "formatted-message-features-meta"
version = "0.0.0"
edition = "2024"
publish = false
authors = ["you"]

[dev-dependencies]

[dependencies.formatted-message-features]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "2.0.0"
path = "../../../../framework/meta-lib"
default-features = false
