[package]
name = "use-module-meta"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2018"
publish = false

[dependencies.use-module]
path = ".."

[dependencies.numbat-wasm]
version = "0.0.18"
path = "../../../../numbat-wasm"

[dependencies.numbat-wasm-debug]
version = "0.0.18"
path = "../../../../numbat-wasm-debug"
