[package]
name = "forwarder-queue"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2024"
publish = false

[lib]
path = "src/forwarder_queue.rs"

[dependencies.dharitri-sc]
version = "2.0.0"
path = "../../../../framework/base"

[dependencies.dharitri-sc-wasm-adapter]
version = "2.0.0"
path = "../../../../framework/wasm-adapter"
optional = true

[dev-dependencies.dharitri-sc-scenario]
version = "2.0.0"
path = "../../../../framework/scenario"
