[package]
name = "ping-pong-rewa-meta"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2018"
publish = false

[dependencies.ping-pong-rewa]
path = ".."

[dependencies.numbat-wasm-debug]
version = "0.0.18"
path = "../../../../numbat-wasm-debug"
