[package]
name = "pair-meta"
version = "0.0.0"
authors = ["you"]
edition = "2024"
publish = false

[dependencies.order-book-pair]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "2.0.0"
path = "../../../../../framework/meta-lib"
default-features = false
