[package]
name = "digital-cash"
version = "0.0.0"
authors = [ "Dharitri"]
edition = "2024"
publish = false

[lib]
path = "src/digital_cash.rs"

[dependencies.dharitri-sc]
version = "2.0.0"
path = "../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "2.0.0"
path = "../../../framework/scenario"
