[package]
name = "kitty-ownership-meta"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies.kitty-ownership]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "2.0.0"
path = "../../../../../framework/meta-lib"
default-features = false
