[package]
name = "formatted-message-features"
version = "0.0.0"
authors = [ "you",]
edition = "2024"
publish = false

[lib]
path = "src/formatted_message_features.rs"

[dependencies.dharitri-sc]
version = "2.0.0"
path = "../../../framework/base"
features = ["alloc"]

[dev-dependencies.dharitri-sc-scenario]
version = "2.0.0"
features = ["wasmer-experimental"]
path = "../../../framework/scenario"
