[package]
name = "random"
version = "0.0.0"
authors = [ "Dharitri <contact@dharitri.org>",]
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = "2.0.0"
path = "../../../../../framework/base"
