[package]
name = "random"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies.numbat-wasm]
version = "0.0.18"
path = "../../../../../numbat-wasm"
