[package]
name = "crowdfunding-erc20"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2024"
publish = false

[lib]
path = "src/crowdfunding_erc20.rs"

[dependencies.erc20]
path = "../erc20"

[dependencies.dharitri-sc]
version = "2.0.0"
path = "../../../../framework/base"

[dev-dependencies.dharitri-sc-scenario]
version = "2.0.0"
path = "../../../../framework/scenario"

