[package]
name = "proxy-pause-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = ["Dharitri <contact@dharitri.org>"]

[dev-dependencies]

[dependencies.proxy-pause]
path = ".."

[dependencies.numbat-wasm-debug]
version = "0.0.18"
path = "../../../../numbat-wasm-debug"
