[package]
name = "alloc-features"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2024"
publish = false

[lib]
path = "src/alloc_features_main.rs"

[dependencies.dharitri-sc]
version = "2.0.0"
path = "../../../framework/base"
features = ["alloc"]

[dev-dependencies.dharitri-sc-scenario]
version = "2.0.0"
features = ["wasmer-experimental"]
path = "../../../framework/scenario"
