[package]
name = "second-contract-meta"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies.second-contract]
path = ".."

[dependencies.dharitri-sc]
version = "2.0.0"
path = "../../../../../../framework/base"

[dependencies.dharitri-sc-meta-lib]
version = "2.0.0"
path = "../../../../../../framework/meta-lib"
default-features = false
