[package]
name = "empty"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2018"
publish = false

[lib]
path = "src/empty.rs"

[dependencies.numbat-wasm]
version = "0.0.18"
path = "../../../numbat-wasm"

[dev-dependencies.numbat-wasm-debug]
version = "0.0.18"
path = "../../../numbat-wasm-debug"

[dev-dependencies]
num-bigint = "0.4.2"
