[package]
name = "format-tests"
version = "0.0.0"
edition = "2024"
publish = false

[[bin]]
name = "format-tests"
path = "src/format_tests.rs"

[dependencies.dharitri-sc]
version = "=2.0.0"
path = "../../../framework/base"

[dependencies.dharitri-sc-scenario]
version = "=2.0.0"
path = "../../../framework/scenario"

[dependencies.dharitri-chain-vm]
version = "=2.0.0"
path = "../../../chain/vm"

[dev-dependencies]
glob = "0.3.0"

[workspace]
members = ["."]

[dependencies]
hex = "0.4"

