[package]
name = "seed-nft-minter-meta"
version = "0.0.0"
edition = "2024"
publish = false
authors = ["Dharitri <contact@dharitri.org>"]

[dev-dependencies]

[dependencies.seed-nft-minter]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "2.0.0"
path = "../../../../framework/meta-lib"
default-features = false
