[package]
name = "proxy-test-first"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2024"
publish = false

[lib]
path = "src/proxy-test-first.rs"

[dependencies]
hex-literal = "1.0"

[dependencies.dharitri-sc]
version = "2.0.0"
path = "../../../../framework/base"
features = ["alloc"]

[dev-dependencies.dharitri-sc-scenario]
version = "2.0.0"
path = "../../../../framework/scenario"
